Repository ServerIbraimovUa/agua_vivo_app, pull requests merged in 2024-01, with the labels that each got.

#1 added fonts
  src/assets/fonts/Roboto-Bold.ttf
  src/assets/fonts/Roboto-Medium.ttf
  src/assets/fonts/Roboto-Regular.ttf
  src/index.css
  src/main.tsx
Labels: enhancement

#2 fix git workflows and pages type
  .github/workflows/deploy.yml
  src/App.tsx
  src/components/PrivateRoute/PrivateRote.tsx
  src/components/PublicRoute/PublicRoute.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/WelcomePage.tsx
Labels: bug

#3 added basename
  src/main.tsx
Labels: bug

#6 fix routers
  src/App.tsx
  src/components/Layout/Layout.tsx
Labels: bug

#10 Welcome page
  src/components/WelcomeList/WelcomeList.styled.ts
  src/components/WelcomeList/WelcomeList.tsx
  src/pages/WelcomePage.tsx
Labels: enhancement

#11 Added styles to welcome ul, li
  src/components/WelcomeList/WelcomeList.styled.ts
  src/components/WelcomeList/WelcomeList.tsx
  src/pages/WelcomePage.tsx
Labels: enhancement

#12 delated import of react
  src/components/WelcomeList/WelcomeList.tsx
  src/pages/WelcomePage.tsx
Labels: enhancement

#14 added modal
  src/components/Modal/Modal.styled.ts
  src/components/Modal/Modal.tsx
  src/index.css
  src/pages/HomePage.tsx
Labels: enhancement

#15 Added AuthForm
  package-lock.json
  package.json
  src/components/AuthForm/AuthForm.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
Labels: enhancement

#16 Component WaterList
  package-lock.json
  src/components/WaterList/AddWaterForm/AddWaterForm.tsx
  src/components/WaterList/WaterList.tsx
  src/pages/HomePage.tsx
Labels: enhancement

#17 Update AuthForm.tsx
  src/components/AuthForm/AuthForm.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
Labels: enhancement

#18 Complete redux setup
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/redux/auth/auth.operations.ts
  src/redux/auth/authSelectors.ts
  src/redux/auth/authSlice.ts
  src/redux/redux_ts/hook.ts
  src/redux/redux_ts/interfaces.ts
  src/redux/store.ts
  src/redux/water/water.operations.ts
  src/redux/water/waterSelectors.ts
  src/redux/water/waterSlice.ts
Labels: enhancement

#19 fixel AddWaterModal
  src/components/WaterList/AddWaterForm/AddWaterForm.tsx
  src/components/WaterList/AddWaterModal/AddWaterModal.tsx
  src/components/WaterList/WaterList.tsx
  src/pages/HomePage.tsx
Labels: enhancement

#20 added sprite and fc icon
  src/assets/images/sprite.svg
  src/components/Icon/Icon.tsx
  src/components/Modal/Modal.styled.ts
  src/components/Modal/Modal.tsx
Labels: enhancement

#22 added global styles
  src/components/Modal/Modal.styled.ts
  src/index.css
  src/main.ts
  src/main.tsx
  src/pages/HomePage.tsx
Labels: enhancement

#23 added setting modal window opening
  src/components/Header/SettingModal/SettingModal.tsx
  src/components/Header/UserLogo/UserLogo.tsx
Labels: enhancement

#26 added css
  package-lock.json
  package.json
  src/css/deviceSize.ts
  src/css/reset.css
  src/index.css
  src/main.ts
Labels: enhancement

#24 Popover added and buttons works for settings and logout
  src/components/Header/Header.tsx
  src/components/Header/UserLogo/UserLogo.tsx
  src/components/Header/UserLogoModal/UserLogoModal.styled.ts
  src/components/Header/UserLogoModal/UserLogoModal.tsx
  src/components/hooks/useOutsideClick.tsx
Labels: enhancement

#27 fix css styles
  src/components/Modal/Modal.styled.ts
  src/main.ts
Labels: enhancement

#25 added dispatch in Authform
  src/components/AuthForm/AuthForm.tsx
  src/redux/auth/auth.operations.ts
Labels: bug, enhancement

#28 fix header
  src/components/Header/Header.tsx
  src/components/Header/UserLogoModal/UserLogoModal.tsx
  src/hooks/useOutsideClick.tsx
Labels: enhancement

#29 fix redux
  src/redux/auth/auth.operations.ts
  src/redux/auth/authSlice.ts
  src/redux/redux_ts/interfaces.ts
  src/redux/water/water.operations.ts
  src/redux/water/waterSlice.ts
Labels: enhancement

#31 create component DailyNorma
  src/components/DailyNorma/DailyNorma.styled.ts
  src/components/DailyNorma/DailyNorma.tsx
  src/components/DailyNorma/DailyNormaModal.tsx
  src/components/Modal/Modal.styled.ts
  src/components/Modal/Modal.tsx
  src/pages/HomePage.tsx
Labels: enhancement

#30 logic add, delete, uptate water
  src/components/WaterList/AddWaterModal/AddWaterModal.tsx
  src/components/WaterList/WaterList.tsx
  src/redux/water/water.operations.ts
Labels: enhancement, wontfix

#33 added logic auth and private publick route
  src/App.tsx
  src/components/AuthForm/AuthForm.tsx
  src/components/Header/Header.tsx
  src/components/Header/Logo/Logo.tsx
  src/components/Header/UserLogoModal/UserLogoModal.tsx
  src/components/Header/UserLogoutModal/UserLogoutModal.tsx
  src/components/PrivateRoute/PrivateRote.tsx
  src/components/PublicRoute/PublicRoute.tsx
  src/redux/auth/auth.operations.ts
  src/redux/auth/authSlice.ts
  src/redux/redux_ts/interfaces.ts
Labels: enhancement

#36 ReactHookForm, update addModal, deleteModal
  src/components/WaterList/AddWaterModal/AddWaterModal.tsx
  src/components/WaterList/DeleteWaterModal/DeleteWaterModal.tsx
  src/components/WaterList/WaterList.tsx
  src/components/WaterList/WaterListItem/WaterListItem.tsx
  src/redux/water/water.operations.ts
Labels: enhancement

#39 avatar on settingModal
  src/components/Header/SettingModal/SettingModal.styled.ts
  src/components/Header/SettingModal/SettingModal.tsx
  src/redux/auth/auth.operations.ts
Labels: enhancement

#42 Header
  src/assets/images/sprite.svg
  src/components/Header/Header.style.tsx
  src/components/Header/Header.tsx
  src/components/Header/Logo/Logo.Styled.ts
  src/components/Header/Logo/Logo.tsx
  src/components/Header/UserAuth/UserAuth.styled.tsx
  src/components/Header/UserAuth/UserAuth.tsx
  src/components/Header/UserLogoModal/PrifileImageEmail.tsx
  src/components/Header/UserLogoModal/UserLogoModal.tsx
  src/img/Logo.svg
  src/img/user.svg
Labels: enhancement

#43 fix thunk
  src/redux/auth/auth.operations.ts
  src/redux/auth/authSlice.ts
Labels: duplicate

#41 Water ratio
  package-lock.json
  package.json
  src/components/WaterRatio/WaterRatio.styled.ts
  src/components/WaterRatio/WaterRatio.tsx
  src/main.ts
  src/pages/HomePage.tsx
  src/redux/redux_ts/interfaces.ts
  src/redux/water/waterSlice.ts
Labels: enhancement

#40 added eye-icon
  src/assets/images/sprite.svg
  src/components/AuthForm/AuthForm.tsx
  src/utils/togglePassword.ts
Labels: enhancement, help wanted

#45 Welcome page
  src/assets/images/Back_Main_Desc1.png
  src/assets/images/Back_Main_Desc2.png
  src/assets/images/Back_Main_Mob1.png
  src/assets/images/Back_Main_Tab1.png
  src/components/WaterConsumptionTracker/WaterConsumptionTracker.tsx
  src/components/WaterConsumptionTracker/WaterConsumptionTrackerStyled.styled.ts
  src/components/WhyDrinkWater/WhyDrinkWater.tsx
  src/components/WhyDrinkWater/WhyDrinkWaterStyled.styled.ts
  src/img/Background_Main_Page.svg
  src/pages/WelcomePage.tsx
Labels: enhancement

#48 update DailyNorma
  src/components/DailyNorma/DailyNorma.styled.ts
  src/components/DailyNorma/DailyNorma.tsx
  src/components/DailyNorma/DailyNormaModal.tsx
  src/components/Modal/Modal.styled.ts
  src/components/Modal/Modal.tsx
  src/main.ts
  src/redux/auth/auth.operations.ts
Labels: enhancement

#49 styled setting modal
  src/components/Header/SettingModal/SettingModal.styled.ts
  src/components/Header/SettingModal/SettingModal.tsx
Labels: enhancement

#46 added alert
  src/components/AuthForm/AuthForm.tsx
Labels: bug, help wanted, invalid

#47 Started adding styles
  src/components/AuthForm/AuthForm.styled.ts
  src/components/AuthForm/AuthForm.tsx
Labels: bug, enhancement

#52 Header - Icons for popover added
  src/assets/images/sprite.svg
  src/components/Header/UserLogoModal/UserLogoModal.styled.ts
  src/components/Header/UserLogoModal/UserLogoModal.tsx
  src/img/Sign_in_def_logo-converted.svg
  src/img/eye-slash-converted.svg
  src/img/eye-slash.svg
Labels: enhancement

#54 Welcome page
  src/components/WaterConsumptionTracker/WaterConsumptionTracker.tsx
  src/components/WaterConsumptionTracker/WaterConsumptionTrackerStyled.styled.ts
  src/components/WhyDrinkWater/WhyDrinkWaterStyled.styled.ts
  src/pages/WelcomePage.tsx
Labels: enhancement

#57 added styles to welxcome page
  src/components/WaterConsumptionTracker/WaterConsumptionTracker.tsx
  src/components/WaterConsumptionTracker/WaterConsumptionTrackerStyled.styled.ts
  src/components/WhyDrinkWater/WhyDrinkWaterStyled.styled.ts
  src/main.ts
  src/pages/WelcomePage.tsx
Labels: enhancement

#55 added preview avatar
  src/components/Header/SettingModal/SettingModal.tsx
Labels: enhancement

#56 Added forgot pass
  src/components/AuthForm/AuthForm.styled.ts
  src/components/AuthForm/AuthForm.tsx
  src/pages/ForgotPasswordPage.tsx
  src/pages/LoginPage.tsx
Labels: enhancement

#58 modal styles added
  src/components/Header/UserLogoModal/UserLogoModal.styled.ts
  src/components/Header/UserLogoModal/UserLogoModal.tsx
  src/components/Header/UserLogoutModal/UserLogautModal.styled.tsx
  src/components/Header/UserLogoutModal/UserLogoutModal.tsx
  src/components/Modal/Modal.styled.ts
  src/img/minus.svg
Labels: enhancement

#60 Add modal on add modal btn
  src/components/Calendar/Calendar.styled.ts
  src/components/Calendar/Calendar.tsx
  src/components/Header/SettingModal/SettingModal.styled.ts
  src/components/Header/UserLogoModal/UserLogoModal.styled.ts
  src/components/Modal/Modal.styled.ts
  src/components/WaterRatio/WaterRatio.tsx
  src/css/deviceSize.ts
  src/css/reset.css
  src/main.ts
  src/redux/auth/authSlice.ts
Labels: duplicate

#61 Added styles
  src/components/AuthForm/AuthForm.styled.ts
  src/components/AuthForm/AuthForm.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
Labels: enhancement

#66 Fix style
  src/components/Calendar/Calendar.styled.ts
  src/components/Calendar/Calendar.tsx
Labels: enhancement

#65 refactored auth & users & water in redux
  src/components/DailyNorma/DailyNormaModal.tsx
  src/components/Header/SettingModal/SettingModal.tsx
  src/components/WaterList/AddWaterModal/AddWaterModal.tsx
  src/components/WaterList/DeleteWaterModal/DeleteWaterModal.tsx
  src/components/WaterList/WaterList.tsx
  src/components/WaterList/WaterListItem/WaterListItem.tsx
  src/redux/auth/auth.operations.ts
  src/redux/auth/authSelectors.ts
  src/redux/auth/authSlice.ts
  src/redux/redux_ts/interfaces.ts
  src/redux/services/handleToken.ts
  src/redux/water/water.operations.ts
  src/redux/water/waterSlice.ts
Labels: duplicate

#67 Added styles
  src/components/AuthForm/AuthForm.styled.ts
  src/components/AuthForm/AuthForm.tsx
  src/main.ts
  src/pages/LoginPage.tsx
Labels: enhancement

#68 changed type of password input
  src/components/Header/SettingModal/SettingModal.styled.ts
  src/components/Header/SettingModal/SettingModal.tsx
Labels: enhancement

#74 small fix cursor
  src/components/Calendar/Calendar.styled.ts
  src/components/Calendar/Calendar.tsx
  src/components/Header/UserLogoModal/UserLogoModal.styled.ts
  src/components/Header/UserLogoutModal/UserLogautModal.styled.tsx
  src/components/WaterRatio/WaterRatio.tsx
  src/main.ts
  src/pages/HomePage.tsx
Labels: duplicate

#76 Setting fix
  src/components/Header/SettingModal/SettingModal.styled.ts
  src/components/Header/SettingModal/SettingModal.tsx
  src/redux/auth/auth.operations.ts
  src/redux/auth/authSlice.ts
  src/redux/redux_ts/interfaces.ts
Labels: enhancement
