Repository ServerIbraimovUa/agua_vivo_app, pull requests merged in 2024-02, with the labels that each got.

#73 added styles and bg desktop
  src/assets/images/Back_sign.png
  src/components/AuthForm/AuthForm.styled.ts
  src/components/AuthForm/AuthForm.tsx
  src/main.ts
  src/pages/RegisterPage.tsx
Labels: bug, enhancement

#77 fix
  src/components/Header/SettingModal/SettingModal.tsx
  src/components/Header/UserLogoModal/UserLogoModal.tsx
  src/components/WaterRatio/WaterRatio.tsx
  src/pages/HomePage.tsx
  src/redux/auth/auth.operations.ts
Labels: enhancement

#78 Water list branch
  src/components/WaterList/AddWaterModal/AddWaterModal.tsx
  src/components/WaterList/DeleteWaterModal/DeleteWaterModal.tsx
  src/components/WaterList/WaterList.styled.ts
  src/components/WaterList/WaterList.tsx
  src/components/WaterList/WaterListItem/WaterListItem.tsx
  src/components/WaterRatio/WaterRatio.tsx
  src/redux/redux_ts/interfaces.ts
  src/redux/water/waterSelectors.ts
  src/redux/water/waterSlice.ts
Labels: enhancement

#80 fix waterRatio percentage & redux
  src/components/WaterRatio/WaterRatio.tsx
  src/pages/HomePage.tsx
  src/redux/auth/auth.operations.ts
  src/redux/redux_ts/interfaces.ts
  src/redux/water/water.operations.ts
  src/redux/water/waterSelectors.ts
  src/redux/water/waterSlice.ts
Labels: duplicate

#82 waterRatio
  src/components/WaterRatio/WaterRatio.tsx
Labels: duplicate

#84 added bg desk signUp
  src/components/AuthForm/AuthForm.styled.ts
Labels: enhancement

#85 added img
  src/assets/images/BackSignUpDesk.png
  src/components/AuthForm/AuthForm.styled.ts
Labels: enhancement

#88 fix popover header
  src/components/Header/UserLogoModal/UserLogoModal.styled.ts
  src/components/Header/UserLogoModal/UserLogoModal.tsx
Labels: enhancement

#91 Added all bg and positions
  src/assets/images/BackAuthMob.png
  src/assets/images/BackAuthTab.png
  src/assets/images/BackSignInDesk.png
  src/components/AuthForm/AuthForm.styled.ts
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
Labels: enhancement

#90 Welcome
  src/assets/images/Back_Main_Tab2.png
  src/assets/images/Welcome-bg-dsc.png
  src/assets/images/WelcomeDeskt.png
  src/assets/images/WelcomeTab.png
  src/components/Header/Header.tsx
  src/main.ts
  src/pages/WelcomePage.tsx
Labels: enhancement

#100 update waterComponents, styled
  package-lock.json
  package.json
  src/components/DailyNorma/DailyNorma.styled.ts
  src/components/WaterList/AddWaterModal/AddWaterModal.tsx
  src/components/WaterList/DeleteWaterModal/DeleteWaterModal.tsx
  src/components/WaterList/WaterList.styled.ts
  src/pages/HomePage/HomePage.styled.ts
  src/redux/water/waterSlice.ts
Labels: enhancement

#95 fix styled
  src/components/Header/SettingModal/SettingModal.styled.ts
  src/components/Header/SettingModal/SettingModal.tsx
Labels: bug, enhancement

#99 Welcome
  src/assets/images/WelcomeDesk.png
  src/assets/images/welcome-desk.png
  src/assets/images/welcome-tab.png
  src/assets/images/welcomeMob.png
  src/components/WhyDrinkWater/WhyDrinkWaterStyled.styled.ts
Labels: enhancement

#97 Added bg position and toastify
  package-lock.json
  package.json
  src/App.tsx
  src/components/AuthForm/AuthForm.styled.ts
  src/components/AuthForm/AuthForm.tsx
  src/main.tsx
  src/redux/auth/authSlice.ts
  src/redux/water/waterSlice.ts
Labels: bug, enhancement, help wanted

#103 Calendar
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarModal.tsx
  src/main.tsx
  src/redux/water/water.operations.ts
  src/redux/water/waterSlice.ts
Labels: enhancement

#104 Update Calendar.tsx
  src/components/Calendar/Calendar.tsx
Labels: bug

#107 Added forgotpass and resetpass pages
  src/App.tsx
  src/components/AuthForm/AuthForm.tsx
  src/components/ForgotPasswordForm/ForgoPasswordForm.styled.ts
  src/components/ForgotPasswordForm/ForgotPasswordForm.tsx
  src/components/ResetPasswordForm/ResetPasswordForm.styled.ts
  src/components/ResetPasswordForm/ResetPasswordForm.tsx
  src/pages/ForgotPasswordPage.tsx
  src/pages/LoginPage.tsx
  src/pages/ResetPasswordPage.tsx
Labels: enhancement

#108 small fix styles geader,welcome,tostify
  src/components/Header/Header.style.ts
  src/components/Header/UserLogoModal/UserLogoModal.tsx
  src/components/WaterRatio/WaterRatio.tsx
  src/components/WhyDrinkWater/WhyDrinkWaterStyled.styled.ts
  src/hooks/useWaterPercentage.ts
  src/main.ts
  src/main.tsx
  src/redux/water/water.operations.ts
  src/redux/water/waterSlice.ts
Labels: enhancement

#111 hover for sign in added
  src/components/Header/UserAuth/UserAuth.styled.ts
Labels: enhancement

#112 we are completed forgot and reset password
  src/App.tsx
  src/components/ForgotPasswordForm/ForgotPasswordForm.tsx
  src/components/ResetPasswordForm/ResetPasswordForm.tsx
  src/pages/ForgotPasswordPage.tsx
  src/pages/LoginPage.tsx
  src/redux/auth/auth.operations.ts
  src/redux/auth/authSlice.ts
Labels: enhancement

#113 Verify email
  src/App.tsx
  src/components/AuthForm/AuthForm.tsx
  src/components/PrivateRoute/PrivateRote.tsx
  src/pages/VerificationPage/VerificationPage.tsx
  src/redux/auth/authSlice.ts
  src/redux/services/handleToken.ts
Labels: enhancement

#116 resend verify email
  src/components/AuthForm/AuthForm.tsx
  src/pages/VerificationPage/VerificationPage.tsx
  src/redux/auth/auth.operations.ts
Labels: enhancement

#117 links changed
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
  src/redux/services/handleToken.ts
Labels: fix

#114 update components AddWater, EditWater, WaterList, WaterListItem + styles
  package-lock.json
  package.json
  src/assets/images/sprite.svg
  src/components/DailyNorma/DailyNorma.styled.ts
  src/components/WaterList/AddWaterModal/AddWaterModal.tsx
  src/components/WaterList/EditWaterModal/EditWaterModal.tsx
  src/components/WaterList/WaterList.styled.ts
  src/components/WaterList/WaterList.tsx
  src/components/WaterList/WaterListItem/WaterListItem.tsx
  src/components/WaterList/utils/utils.tsx
  src/redux/water/water.operations.ts
Labels: enhancement

#119 register thunk
  src/redux/auth/authSlice.ts
Labels: fix

#120 update PopoverComponent
  src/assets/images/garage.jpg
  src/assets/images/garage.png
  src/components/DailyNorma/DailyNorma.styled.ts
  src/components/DailyNorma/DailyNormaModal.tsx
  src/components/DailyNorma/Popover.tsx
  src/components/Popover/Popover.styled.ts
  src/components/Popover/Popover.tsx
  src/components/WaterList/AddWaterModal/AddWaterModal.tsx
  src/components/WaterList/EditWaterModal/EditWaterModal.tsx
  src/pages/HomePage/HomePage.styled.ts
  src/pages/VerificationPage/VerificationPage.tsx
Labels: bug, enhancement, fix

#127 fix
  src/components/Calendar/Calendar.styled.ts
  src/components/WaterRatio/WaterRatio.styled.ts
  src/components/WaterRatio/WaterRatio.tsx
Labels: duplicate

#118 added update password
  src/components/Header/SettingModal/SettingModal.styled.ts
  src/components/Header/SettingModal/SettingModal.tsx
  src/redux/redux_ts/interfaces.ts
Labels: bug, enhancement, fix

#125 Update verification page
  src/assets/images/sprite.svg
  src/components/Popover/Popover.styled.ts
  src/components/Popover/Popover.tsx
  src/pages/VerificationPage/VerificationPage.tsx
  src/pages/VerificationPage/VerificationPagestyled.ts
Labels: fix

#126 Added yup schemas on repeat and forgot pages
  src/components/AuthForm/AuthForm.tsx
  src/components/ForgotPasswordForm/ForgotPasswordForm.tsx
  src/components/ResetPasswordForm/ResetPasswordForm.tsx
  src/schemas/authSchemas.ts
Labels: bug, enhancement, fix

#128 fixed bugs
  src/assets/images/sprite.svg
  src/components/DailyNorma/DailyNorma.styled.ts
  src/components/Header/UserLogoutModal/UserLogautModal.styled.ts
  src/components/WaterList/AddWaterModal/AddWaterModal.tsx
  src/components/WaterList/EditWaterModal/EditWaterModal.tsx
  src/components/WaterList/WaterList.styled.ts
  src/components/WaterList/WaterList.tsx
  src/components/WaterList/WaterListItem/WaterListItem.tsx
Labels: enhancement

#129 react tour
  package-lock.json
  package.json
  src/assets/images/sprite.svg
  src/components/DailyNorma/DailyNorma.tsx
  src/components/Header/UserLogo/UserLogo.styled.ts
  src/components/Header/UserLogo/UserLogo.tsx
  src/components/Header/UserLogoModal/UserLogoModal.tsx
  src/components/WaterRatio/WaterRatio.tsx
  src/main.tsx
  src/pages/HomePage/HomePage.tsx
  src/utils/tourSteps.ts
Labels: enhancement

#131 update styles Popover
  src/components/Popover/Popover.styled.ts
  src/pages/VerificationPage/VerificationPagestyled.ts
Labels: fix

#132 fix avatar
  src/components/Header/SettingModal/Avatar/AvatarForm.styled.ts
  src/components/Header/SettingModal/Avatar/AvatarForm.tsx
  src/components/Header/SettingModal/SettingModal.styled.ts
  src/components/Header/SettingModal/SettingModal.tsx
Labels: fix

#134 fix button save
  src/components/Header/SettingModal/SettingModal.tsx
Labels: fix

#141 fixed bugs, customized selector
  package-lock.json
  package.json
  src/components/WaterList/AddWaterModal/AddWaterModal.tsx
  src/components/WaterList/DeleteWaterModal/DeleteWaterModal.tsx
  src/components/WaterList/EditWaterModal/EditWaterModal.tsx
  src/components/WaterList/WaterList.styled.ts
  src/components/WaterList/WaterList.tsx
  src/components/WaterList/WaterListItem/WaterListItem.tsx
  src/pages/VerificationPage/VerificationPage.tsx
  src/redux/redux_ts/interfaces.ts
  src/utils/timePicker.ts
Labels: enhancement

#147 ukrainian language
  package-lock.json
  package.json
  src/assets/images/sprite.svg
  src/components/AuthForm/AuthForm.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarModal.tsx
  src/components/Chart/Chart.tsx
  src/components/DailyNorma/DailyNorma.styled.ts
  src/components/DailyNorma/DailyNorma.tsx
  src/components/DailyNorma/DailyNormaModal.tsx
  src/components/ForgotPasswordForm/ForgotPasswordForm.tsx
  src/components/Header/Language/Language.styled.ts
  src/components/Header/Language/LanguageModal.tsx
  src/components/Header/Language/LanguageSelector.tsx
  src/components/Header/SettingModal/Avatar/AvatarForm.tsx
  src/components/Header/SettingModal/SettingModal.tsx
  src/components/Header/UserAuth/UserAuth.tsx
  src/components/Header/UserLogoModal/UserLogoModal.styled.ts
  src/components/Header/UserLogoModal/UserLogoModal.tsx
  src/components/Header/UserLogoutModal/UserLogoutModal.tsx
  src/components/TeamModal/TeamModal.tsx
  src/components/WaterConsumptionTracker/WaterConsumptionTracker.tsx
  src/components/WaterList/AddWaterModal/AddWaterModal.tsx
  src/components/WaterList/DeleteWaterModal/DeleteWaterModal.tsx
  src/components/WaterList/EditWaterModal/EditWaterModal.tsx
  src/components/WaterList/WaterList.styled.ts
  src/components/WaterList/WaterList.tsx
  src/components/WaterList/WaterListItem/WaterListItem.tsx
  src/components/WaterRatio/WaterRatio.tsx
  src/components/WhyDrinkWater/WhyDrinkWater.tsx
  src/pages/ForgotPasswordPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/VerificationPage/VerificationPage.tsx
  src/utils/i18n.ts
  src/utils/languages/en.json
  src/utils/languages/ua.json
  src/utils/tourSteps.ts
  src/utils/waterIcon.tsx
Labels: documentation, enhancement

#148 deleted import
  src/components/WaterList/WaterListItem/WaterListItem.tsx
Labels: fix

#142 team modal
  src/App.tsx
  src/components/TeamModal/TeamModal.tsx
  src/components/WhyDrinkWater/WhyDrinkWaterStyled.styled.ts
  src/pages/WelcomePage.tsx
  src/pages/WelcomePage/WelcomePage.styled.ts
  src/pages/WelcomePage/WelcomePage.tsx
Labels: enhancement, fix
